base:
  project: SAHeart-project
  random_state: 999
  target_col: target

data_source:
  s3_source: data_given/heart.csv
  

load_data:
  raw_dataset_csv: data/raw/heart.csv

split_data:
  train_path: data/processed/train_SAHeart.csv
  test_path: data/processed/test_SAHeart.csv
  test_size: 0.35